//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNS_VIVIENDAS
    {
        public int Num_paquete { get; set; }
        public byte Est_vivienda_bd { get; set; }
        public System.DateTime Fec_paquete { get; set; }
        public string Cod_dpto { get; set; }
        public string Cod_mpio { get; set; }
        public int Num_ficha { get; set; }
        public string ide_ficha_origen { get; set; }
        public byte ori_encuesta { get; set; }
        public byte Est_ficha { get; set; }
        public byte Tip_vivienda { get; set; }
        public byte Tip_mat_paredes { get; set; }
        public byte Tip_mat_pisos { get; set; }
        public byte Ind_tiene_energia { get; set; }
        public byte Tip_estrato_energia { get; set; }
        public byte Ind_tiene_alcantarillado { get; set; }
        public byte Ind_tiene_gas { get; set; }
        public byte Ind_tiene_recoleccion { get; set; }
        public byte Ind_tiene_acueducto { get; set; }
        public byte Tip_estrato_acueducto { get; set; }
        public byte Num_cuartos_vivienda { get; set; }
        public byte Num_hogares_vivienda { get; set; }
        public string Cod_encuestador { get; set; }
        public string Cod_supervisor { get; set; }
        public string Cod_critico { get; set; }
        public string Cod_digitador { get; set; }
        public Nullable<System.DateTime> Fec_digitacion { get; set; }
        public System.DateTime Fec_ini_vivienda { get; set; }
        public System.DateTime Fec_fin_vivienda { get; set; }
        public string Cod_equipo_encuesta { get; set; }
    }
}
