//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNS_HOGARES
    {
        public int Num_paquete { get; set; }
        public byte Est_hogar_bd { get; set; }
        public System.DateTime Fec_paquete { get; set; }
        public string Cod_dpto { get; set; }
        public string Cod_mpio { get; set; }
        public int Num_ficha { get; set; }
        public string Ide_ficha_origen { get; set; }
        public byte Ide_hogar { get; set; }
        public byte Tip_ocupa_vivienda { get; set; }
        public byte Num_cuartos_exclusivos { get; set; }
        public byte Num_cuartos_dormir { get; set; }
        public byte Num_cuartos_unicos_dormir { get; set; }
        public byte Tip_sanitario { get; set; }
        public byte Tip_ubi_sanitario { get; set; }
        public byte Tip_uso_sanitario { get; set; }
        public byte Tip_origen_agua { get; set; }
        public byte Ind_agua_llega_7dias { get; set; }
        public byte Num_dias_llega { get; set; }
        public byte Ind_agua_llega_24horas { get; set; }
        public byte Num_horas_llega { get; set; }
        public byte Tip_uso_agua_beber { get; set; }
        public byte Tip_elimina_basura { get; set; }
        public byte Ind_tiene_cocina { get; set; }
        public byte Tip_prepara_alimentos { get; set; }
        public byte Tip_uso_cocina { get; set; }
        public byte Tip_energia_cocina { get; set; }
        public byte Ind_tiene_nevera { get; set; }
        public byte Ind_tiene_lavadora { get; set; }
        public byte Ind_tiene_pc { get; set; }
        public byte Ind_tiene_internet { get; set; }
        public byte Ind_tiene_moto { get; set; }
        public byte Ind_tiene_tractor { get; set; }
        public byte Ind_tiene_carro { get; set; }
        public byte Ind_tiene_bien_raiz { get; set; }
        public byte Ind_gasto_alimento { get; set; }
        public int Vlr_gasto_alimento { get; set; }
        public byte Ind_gasto_transporte { get; set; }
        public int Vlr_gasto_transporte { get; set; }
        public byte Ind_gasto_educacion { get; set; }
        public int Vlr_gasto_educacion { get; set; }
        public byte Ind_gasto_salud { get; set; }
        public int Vlr_gasto_salud { get; set; }
        public byte Ind_gasto_serv_publicos { get; set; }
        public int Vlr_gasto_serv_publicos { get; set; }
        public byte Ind_gasto_celular { get; set; }
        public int Vlr_gasto_celular { get; set; }
        public byte Ind_gasto_arriendo { get; set; }
        public int Vlr_gasto_arriendo { get; set; }
        public byte Ind_gasto_otros { get; set; }
        public int Vlr_gasto_otros { get; set; }
        public int Vlr_total_gastos { get; set; }
        public byte Num_habita_vivienda { get; set; }
        public byte Ind_evento_inundacion { get; set; }
        public byte Num_evento_inundacion { get; set; }
        public byte Ind_evento_avalancha { get; set; }
        public byte Num_evento_avalancha { get; set; }
        public byte Ind_evento_terremoto { get; set; }
        public byte Num_evento_terremoto { get; set; }
        public byte Ind_evento_incendio { get; set; }
        public byte Num_evento_incendio { get; set; }
        public byte Ind_evento_vendaval { get; set; }
        public byte Num_evento_vendaval { get; set; }
        public byte Ind_evento_hundimiento { get; set; }
        public byte Num_evento_hundimiento { get; set; }
        public byte Num_personas_posibles { get; set; }
        public byte Num_personas_hogar { get; set; }
        public System.DateTime fec_ini_visita1 { get; set; }
        public System.DateTime fec_fin_visita1 { get; set; }
        public byte res_visita1 { get; set; }
        public Nullable<System.DateTime> fec_ini_visita2 { get; set; }
        public Nullable<System.DateTime> fec_fin_visita2 { get; set; }
        public Nullable<byte> res_visita2 { get; set; }
        public byte Ide_informante { get; set; }
        public string Pri_nom_informante { get; set; }
        public string Seg_nom_informante { get; set; }
        public string Pri_ape_informante { get; set; }
        public string Seg_ape_informante { get; set; }
        public byte tip_informante { get; set; }
        public string Ide_firma_informante { get; set; }
        public byte Cau_sin_firma { get; set; }
        public string Email_contacto { get; set; }
        public string Num_tel_contacto { get; set; }
        public Nullable<byte> Ind_declaracion { get; set; }
        public Nullable<System.DateTime> ML_Procesado { get; set; }
        public Nullable<bool> ML_Irregular { get; set; }
    }
}
