//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNS_PERSONAS_Logs
    {
        public long Id { get; set; }
        public int Num_paquete { get; set; }
        public string Cod_dpto { get; set; }
        public string Cod_mpio { get; set; }
        public int Num_ficha { get; set; }
        public byte Ide_hogar { get; set; }
        public byte Ide_persona { get; set; }
        public System.DateTime Fec_evaluado { get; set; }
        public double Fec_nacimiento { get; set; }
        public double Grado_alcanzado { get; set; }
        public double Ind_acudio_salud { get; set; }
        public double Ind_conyuge_vive_hogar { get; set; }
        public double Ind_discap_bañarse { get; set; }
        public double Ind_discap_entender { get; set; }
        public double Ind_discap_hablar { get; set; }
        public double Ind_discap_moverse { get; set; }
        public double Ind_discap_ninguna { get; set; }
        public double Ind_discap_oir { get; set; }
        public double Ind_discap_salir { get; set; }
        public double Ind_discap_ver { get; set; }
        public double Ind_enfermo_30 { get; set; }
        public double Ind_esta_embarazada { get; set; }
        public double Ind_estudia { get; set; }
        public double Ind_fondo_pensiones { get; set; }
        public double Ind_fue_atendido_salud { get; set; }
        public double Ind_ingr_arriendos { get; set; }
        public double Ind_ingr_cosecha { get; set; }
        public double Ind_ingr_estado { get; set; }
        public double Ind_ingr_honorarios { get; set; }
        public double Ind_ingr_pension { get; set; }
        public double Ind_ingr_remesa_exterior { get; set; }
        public double Ind_ingr_remesa_pais { get; set; }
        public double Ind_ingr_salario { get; set; }
        public double Ind_leer_escribir { get; set; }
        public double Ind_otros_ingresos { get; set; }
        public double Ind_padre_vive_hogar { get; set; }
        public double Ind_pariente_domestico { get; set; }
        public double Ind_recibe_comida { get; set; }
        public double Ind_tuvo_hijos { get; set; }
        public double Niv_educativo { get; set; }
        public double Num_mes_ingr_cosecha { get; set; }
        public double Num_sem_buscando { get; set; }
        public double Sexo_persona { get; set; }
        public double Tip_actividad_mes { get; set; }
        public double Tip_cuidado_niños { get; set; }
        public double Tip_documento { get; set; }
        public double Tip_empleado { get; set; }
        public double Tip_estado_civil { get; set; }
        public double Tip_parentesco { get; set; }
        public double Tip_Seg_social { get; set; }
        public double Vlr_ingr_arriendos { get; set; }
        public double Vlr_ingr_col_mayor { get; set; }
        public double Vlr_ingr_cosecha { get; set; }
        public double Vlr_ingr_fam_accion { get; set; }
        public double Vlr_ingr_honorarios { get; set; }
        public double Vlr_ingr_otro_subsidio { get; set; }
        public double Vlr_ingr_pension { get; set; }
        public double Vlr_ingr_remesa_exterior { get; set; }
        public double Vlr_ingr_remesa_pais { get; set; }
        public double Vlr_ingr_salario { get; set; }
        public double Vlr_otros_ingresos { get; set; }
    }
}
