//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SISBEN_IVEntities : DbContext
    {
        public SISBEN_IVEntities()
            : base("name=SISBEN_IVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CNS_CONTROL_ENVIOS> CNS_CONTROL_ENVIOS { get; set; }
        public virtual DbSet<CNS_FICHAS> CNS_FICHAS { get; set; }
        public virtual DbSet<CNS_HOGARES> CNS_HOGARES { get; set; }
        public virtual DbSet<CNS_HOGARES_FICHA> CNS_HOGARES_FICHA { get; set; }
        public virtual DbSet<CNS_HOGARES_RECHAZO> CNS_HOGARES_RECHAZO { get; set; }
        public virtual DbSet<CNS_PERSONAS> CNS_PERSONAS { get; set; }
        public virtual DbSet<CNS_VIVIENDAS> CNS_VIVIENDAS { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOS { get; set; }
        public virtual DbSet<CNS_CategorySets> CNS_CategorySets { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIOS { get; set; }
        public virtual DbSet<CNS_HOGARES_Logs> CNS_HOGARES_Logs { get; set; }
        public virtual DbSet<CNS_PERSONAS_Logs> CNS_PERSONAS_Logs { get; set; }
        public virtual DbSet<CNS_VIVIENDAS_Logs> CNS_VIVIENDAS_Logs { get; set; }
    
        public virtual int sp__ClasificarProximoHogar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp__ClasificarProximoHogar");
        }
    
        public virtual ObjectResult<sp__DAT_Departamentos__Get_Result> sp__DAT_Departamentos__Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp__DAT_Departamentos__Get_Result>("sp__DAT_Departamentos__Get");
        }
    
        public virtual ObjectResult<sp__Municipios__GetByDpto_Result> sp__Municipios__GetByDpto(string cod_dpto)
        {
            var cod_dptoParameter = cod_dpto != null ?
                new ObjectParameter("cod_dpto", cod_dpto) :
                new ObjectParameter("cod_dpto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp__Municipios__GetByDpto_Result>("sp__Municipios__GetByDpto", cod_dptoParameter);
        }
    }
}
