//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CNS_HOGARES_Logs", Schema = "ML")]
    public partial class CNS_HOGARES_Logs
    {
        public long Id { get; set; }
        public int Num_paquete { get; set; }
        public string Cod_dpto { get; set; }
        public string Cod_mpio { get; set; }
        public int Num_ficha { get; set; }
        public byte Ide_hogar { get; set; }
        public System.DateTime Fec_evaluado { get; set; }
        public double Tip_ocupa_vivienda { get; set; }
        public double Num_cuartos_exclusivos { get; set; }
        public double Num_cuartos_dormir { get; set; }
        public double Num_cuartos_unicos_dormir { get; set; }
        public double Tip_sanitario { get; set; }
        public double Tip_ubi_sanitario { get; set; }
        public double Tip_uso_sanitario { get; set; }
        public double Tip_origen_agua { get; set; }
        public double Ind_agua_llega_7dias { get; set; }
        public double Num_dias_llega { get; set; }
        public double Ind_agua_llega_24horas { get; set; }
        public double Num_horas_llega { get; set; }
        public double Tip_uso_agua_beber { get; set; }
        public double Tip_elimina_basura { get; set; }
        public double Ind_tiene_cocina { get; set; }
        public double Tip_prepara_alimentos { get; set; }
        public double Tip_uso_cocina { get; set; }
        public double Tip_energia_cocina { get; set; }
        public double Ind_tiene_nevera { get; set; }
        public double Ind_tiene_lavadora { get; set; }
        public double Ind_tiene_pc { get; set; }
        public double Ind_tiene_internet { get; set; }
        public double Ind_tiene_moto { get; set; }
        public double Ind_tiene_tractor { get; set; }
        public double Ind_tiene_carro { get; set; }
        public double Ind_tiene_bien_raiz { get; set; }
        public double Ind_gasto_alimento { get; set; }
        public double Vlr_gasto_alimento { get; set; }
        public double Ind_gasto_transporte { get; set; }
        public double Vlr_gasto_transporte { get; set; }
        public double Ind_gasto_educacion { get; set; }
        public double Vlr_gasto_educacion { get; set; }
        public double Ind_gasto_salud { get; set; }
        public double Vlr_gasto_salud { get; set; }
        public double Ind_gasto_serv_publicos { get; set; }
        public double Vlr_gasto_serv_publicos { get; set; }
        public double Ind_gasto_celular { get; set; }
        public double Vlr_gasto_celular { get; set; }
        public double Ind_gasto_arriendo { get; set; }
        public double Vlr_gasto_arriendo { get; set; }
        public double Ind_gasto_otros { get; set; }
        public double Vlr_gasto_otros { get; set; }
        public double Vlr_total_gastos { get; set; }
        public double Num_habita_vivienda { get; set; }
        public double Ind_evento_inundacion { get; set; }
        public double Num_evento_inundacion { get; set; }
        public double Ind_evento_avalancha { get; set; }
        public double Num_evento_avalancha { get; set; }
        public double Ind_evento_terremoto { get; set; }
        public double Num_evento_terremoto { get; set; }
        public double Ind_evento_incendio { get; set; }
        public double Num_evento_incendio { get; set; }
        public double Ind_evento_vendaval { get; set; }
        public double Num_evento_vendaval { get; set; }
        public double Ind_evento_hundimiento { get; set; }
        public double Num_evento_hundimiento { get; set; }
        public double Num_personas_posibles { get; set; }
        public double Num_personas_hogar { get; set; }
        public double res_visita { get; set; }
    }
}
