//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CNS_VIVIENDAS_Logs", Schema = "ML")]
    public partial class CNS_VIVIENDAS_Logs
    {
        public long Id { get; set; }
        public int Num_paquete { get; set; }
        public string Cod_dpto { get; set; }
        public string Cod_mpio { get; set; }
        public int Num_ficha { get; set; }
        public byte Ide_hogar { get; set; }
        public System.DateTime Fec_evaluado { get; set; }
        public double Tip_vivienda { get; set; }
        public double Tip_mat_paredes { get; set; }
        public double Tip_mat_pisos { get; set; }
        public double Ind_tiene_energia { get; set; }
        public double Tip_estrato_energia { get; set; }
        public double Ind_tiene_alcantarillado { get; set; }
        public double Ind_tiene_gas { get; set; }
        public double Ind_tiene_recoleccion { get; set; }
        public double Ind_tiene_acueducto { get; set; }
        public double Tip_estrato_acueducto { get; set; }
        public double Num_cuartos_vivienda { get; set; }
        public double Num_hogares_vivienda { get; set; }
    }
}
