//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CNS_PERSONAS", Schema = "DAT")]
    public partial class CNS_PERSONAS
    {
        public int Num_paquete { get; set; }
        public byte Est_persona_bd { get; set; }
        public System.DateTime Fec_paquete { get; set; }
        public string Cod_dpto { get; set; }
        public string Cod_mpio { get; set; }
        public int Num_ficha { get; set; }
        public string Ide_ficha_origen { get; set; }
        public byte Ide_hogar { get; set; }
        public byte Ide_persona { get; set; }
        public int Ide_nacional { get; set; }
        public byte Ind_escaner { get; set; }
        public string Pri_apellido { get; set; }
        public string Seg_apellido { get; set; }
        public string Pri_nombre { get; set; }
        public string Seg_nombre { get; set; }
        public byte Sexo_persona { get; set; }
        public byte Ori_persona { get; set; }
        public byte Tip_documento { get; set; }
        public string Num_documento { get; set; }
        public System.DateTime Fec_nacimiento { get; set; }
        public byte Edad_calculada { get; set; }
        public string Fec_documento { get; set; }
        public string Cod_dpto_documento { get; set; }
        public string Cod_mpio_documento { get; set; }
        public string Cod_pais_documento { get; set; }
        public byte Tip_parentesco { get; set; }
        public byte Tip_estado_civil { get; set; }
        public byte Ind_conyuge_vive_hogar { get; set; }
        public byte Ide_conyuge { get; set; }
        public byte Ind_padre_vive_hogar { get; set; }
        public byte Ide_padre { get; set; }
        public byte Ind_pariente_domestico { get; set; }
        public byte Ide_serv_domestico { get; set; }
        public byte Ind_discap_ver { get; set; }
        public byte Ind_discap_oir { get; set; }
        public byte Ind_discap_hablar { get; set; }
        public byte Ind_discap_moverse { get; set; }
        public byte Ind_discap_bañarse { get; set; }
        public byte Ind_discap_salir { get; set; }
        public byte Ind_discap_entender { get; set; }
        public byte Ind_discap_ninguna { get; set; }
        public byte Tip_Seg_social { get; set; }
        public byte Ind_enfermo_30 { get; set; }
        public byte Ind_acudio_salud { get; set; }
        public byte Ind_fue_atendido_salud { get; set; }
        public byte Ind_esta_embarazada { get; set; }
        public byte Ind_tuvo_hijos { get; set; }
        public byte Tip_cuidado_niños { get; set; }
        public byte Ind_recibe_comida { get; set; }
        public byte Ind_leer_escribir { get; set; }
        public byte Ind_estudia { get; set; }
        public byte Niv_educativo { get; set; }
        public byte Grado_alcanzado { get; set; }
        public byte Ind_fondo_pensiones { get; set; }
        public byte Tip_actividad_mes { get; set; }
        public int Num_sem_buscando { get; set; }
        public byte Tip_empleado { get; set; }
        public byte Ind_ingr_salario { get; set; }
        public int Vlr_ingr_salario { get; set; }
        public byte Ind_ingr_honorarios { get; set; }
        public int Vlr_ingr_honorarios { get; set; }
        public byte Ind_ingr_cosecha { get; set; }
        public byte Num_mes_ingr_cosecha { get; set; }
        public int Vlr_ingr_cosecha { get; set; }
        public byte Ind_ingr_pension { get; set; }
        public int Vlr_ingr_pension { get; set; }
        public byte Ind_ingr_remesa_pais { get; set; }
        public int Vlr_ingr_remesa_pais { get; set; }
        public byte Ind_ingr_remesa_exterior { get; set; }
        public int Vlr_ingr_remesa_exterior { get; set; }
        public byte Ind_ingr_arriendos { get; set; }
        public int Vlr_ingr_arriendos { get; set; }
        public byte Ind_otros_ingresos { get; set; }
        public int Vlr_otros_ingresos { get; set; }
        public byte Ind_ingr_estado { get; set; }
        public int Vlr_ingr_fam_accion { get; set; }
        public int Vlr_ingr_col_mayor { get; set; }
        public int Vlr_ingr_otro_subsidio { get; set; }
        public System.DateTime Fec_ini_persona1 { get; set; }
        public System.DateTime Fec_fin_persona1 { get; set; }
        public System.DateTime Fec_ini_persona2 { get; set; }
        public System.DateTime Fec_fin_persona2 { get; set; }
    }
}
