//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CNS_CONTROL_ENVIOS
    {
        public string cod_dpto { get; set; }
        public string cod_mpio { get; set; }
        public string ide_envio { get; set; }
        public short num_fichas { get; set; }
        public short num_hog_ficha { get; set; }
        public short num_viviendas { get; set; }
        public short num_hogares { get; set; }
        public short num_hog_rechazo { get; set; }
        public short num_personas { get; set; }
        public System.DateTime fec_paquete { get; set; }
        public int num_paquete { get; set; }
        public byte est_control_bd { get; set; }
        public System.DateTime fec_modificacion { get; set; }
    }
}
