//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisben.WebApps.QAML.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("MUNICIPIOS", Schema = "DAT")]
    public partial class MUNICIPIO
    {
        public int cod_mpio { get; set; }
        public int cod_dpto { get; set; }
        public string mpio { get; set; }
    }
}
